import { ReactiveComponent } from '../core/component.js'
import { signal } from '../core/signals.js'
import { componentStyles } from '../shared/component-styles.js'

const styles = componentStyles(`
    .md2pdf-bar { display: flex; gap: 0.5rem; align-items: center; padding: 0.75rem 0; flex-wrap: wrap; }
    .form-row { display: flex; gap: 0.75rem; margin-bottom: 0.75rem; }
    .form-row input { flex: 1; }
    .md-area { width: 100%; min-height: 250px; padding: 0.75rem; border-radius: 8px; font-family: 'JetBrains Mono', monospace; font-size: 0.85rem; resize: vertical; box-sizing: border-box; line-height: 1.5; }
    .preview { background: white; color: #1a1a1a; border-radius: 8px; padding: 1.5rem; margin-top: 0.75rem; font-size: 0.9rem; line-height: 1.6; max-height: 300px; overflow: auto; }
    .preview h1 { font-size: 1.5rem; margin: 0 0 0.5rem; }
    .preview h2 { font-size: 1.2rem; margin: 1rem 0 0.3rem; }
    .preview h3 { font-size: 1rem; margin: 0.8rem 0 0.2rem; }
    .preview code { background: #f0f0f0; padding: 0.1rem 0.3rem; border-radius: 3px; font-size: 0.85em; }
    .preview pre { background: #f5f5f5; padding: 0.75rem; border-radius: 6px; overflow-x: auto; }
    .preview table { border-collapse: collapse; width: 100%; margin: 0.5rem 0; }
    .preview th, .preview td { border: 1px solid #ddd; padding: 0.4rem 0.6rem; text-align: left; }
    .preview th { background: #f0f0f0; }
    .preview ul { padding-left: 1.5rem; }
`)

export class MdToPdfComponent extends ReactiveComponent {
    static styles = styles
    constructor() {
        super()
        this.markdown = signal('')
        this.title = signal('Document')
        this.loading = signal(false)
        this.error = signal('')
        this.result = signal(null)
    }

    async convert() {
        if (!this.markdown.value.trim()) return
        this.loading.value = true
        this.error.value = ''
        this.result.value = null
        try {
            const data = await window.rpc['md-to-pdf'].convert(this.markdown.value, this.title.value)
            if (data.ok) {
                this.result.value = data
            } else {
                this.error.value = data.error || 'Conversion failed'
            }
        } catch (e) {
            this.error.value = e.message
        } finally {
            this.loading.value = false
        }
    }

    loadSample() {
        this.markdown.value = `# Project Report\n\n## Overview\n\nThis is a sample document generated from **Markdown**.\n\n### Features\n\n- Convert headings, lists, and emphasis\n- Generates clean PDF output\n- Pure Python, no heavy frameworks\n\n## Code Example\n\n\`\`\`python\nprint("Hello, PDF!")\n\`\`\`\n\n## Table\n\n| Name | Role | Status |\n|------|------|--------|\n| Alice | Dev | Active |\n| Bob | PM | Review |\n\n---\n\n*Generated by md-to-pdf*`
        this.title.value = 'Project Report'
    }

    render() {
        const { markdown, title, loading, error, result } = this

        return `
        <div class="md2pdf-wrap">
            <div class="section-label">Title</div>
            <div class="form-row">
                <input type="text" .value="${title.value}" @input="${e => title.value = e.target.value}" placeholder="Document title" />
                <button class="btn btn-secondary btn-sm" @click="${this.loadSample}">Load Sample</button>
            </div>
            <div class="section-label">Markdown</div>
            <textarea class="md-area" .value="${markdown.value}" @input="${e => markdown.value = e.target.value}" placeholder="Write your markdown here..."></textarea>
            <div style="margin-top:0.75rem;display:flex;gap:0.5rem;align-items:center;">
                <button class="btn btn-primary" @click="${this.convert}" ${loading || !markdown.value.trim() ? 'disabled' : ''}>
                    ${loading ? 'Converting...' : 'Convert to PDF'}
                </button>
                ${result.value ? `<span style="font-size:0.8rem;opacity:0.6;">${result.value.pages} page${result.value.pages !== 1 ? 's' : ''} generated</span>` : ''}
            </div>
            ${error ? `<div class="error-box">${error}</div>` : ''}
            ${result.value ? `
                <div class="success-box">
                    PDF generated: <strong>${result.value.file}</strong> (${result.value.pages} pages)
                </div>
            ` : ''}
            ${markdown.value ? `
                <div class="section-label" style="margin-top:1rem;">Preview</div>
                <div class="preview">${this._renderMd(markdown.value)}</div>
            ` : ''}
        </div>`
    }

    _renderMd(md) {
        return md
            .replace(/^### (.+)$/gm, '<h3>$1</h3>')
            .replace(/^## (.+)$/gm, '<h2>$1</h2>')
            .replace(/^# (.+)$/gm, '<h1>$1</h1>')
            .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
            .replace(/\*(.+?)\*/g, '<em>$1</em>')
            .replace(/`(.+?)`/g, '<code>$1</code>')
            .replace(/^- (.+)$/gm, '<li>$1</li>')
            .replace(/(<li>.*<\/li>)/s, '<ul>$1</ul>')
            .replace(/^---$/gm, '<hr>')
            .replace(/\n/g, '<br>')
    }
}
